version: '3'
services:
  db:
    container_name: my-group-db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5566:5432
    restart: always
  auth:
    